# permissions for end users to edit runners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: runner-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: runner
    app.kubernetes.io/part-of: runner
    app.kubernetes.io/managed-by: kustomize
  name: runner-editor-role
rules:
- apiGroups:
  - apps.gitlab.com
  resources:
  - runners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.gitlab.com
  resources:
  - runners/status
  verbs:
  - get
